config/routes.rb
Airecel::Application.routes.draw do
  resources :pincodes
  resources :tab_tasks
  #get "accounts/index"
  #get "reports/index"
  resources :serveys, :accounts
  resources :reports
  resources :assignments
  resources :tabs do
    get :autocomplete_pincode_pin_number, :on => :collection
  end

  resources :customers do
   collection do
    post :import
   end
   member do
    get :accept
    post :accpet
    get :reassign
    post :reassign
    get :customer_mapdetail
   end
  end
  resources :users
  resources :sessions , only: [:new,:create,:destroy]
  #match '/residential-verifications',  to: 'assignments#residential_verifications',  via: 'get'
  get "dashboard/residential-verifications" => "assignments#residential_verifications", :as => :residential_verifications
  get "dashboard/office-verifications" => "assignments#office_verifications", :as => :office_verifications

  get "cusomers/completed" => "customers#completed", :as => :completed
  get "cusomers/pending" => "customers#pending", :as => :pending
  get "cusomers/in_progress" => "customers#in_progress", :as => :in_progress
  get "dashboard/index"
  match '/signup',  to: 'users#new',  via: 'get'
  #match '/completed', to: 'appointments#completed', via: 'get'
  match '/login' , to: "sessions#new" , via: "get"
  match '/logout'  ,to: "sessions#destroy" , via: "delete"
  root 'dashboard#index'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :login_required
  #load_and_authorize_resource
  include ApplicationHelper
  def index
   @completed_customers = Customer.where(status: "verified")
   @pending_customers = Customer.where(status: "submitted")
   @in_progress_customers = Customer.where(status: "completed")
   @tab_user_task = current_user.tab.assignments if logged_in? && current_user.tab  #Assignment.where(:tab_id => current_user.tab)
   @assignments = Assignment.where('DATE(created_at) > ? AND DATE(created_at) < ? and customer_office_id Is NULL', Date.today-105, Date.today+1).includes(:user, :customer, :tab)
   @office_assignments = Assignment.where('DATE(created_at) > ? AND DATE(created_at) < ? and customer_id Is NULL', Date.today-105, Date.today+1).includes(:user, :customer, :tab)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_assigned_tasks.html.erb
<p> Assigned Task</p>
	<table class="table table-condensed table-bordered table-striped">
		<tr>
			<th> Tab Name </th>
			<th> Customer Name  </th>
			<th> Status </th>
		</tr>
			<% @assignments.each do |task| %>
<tr>
<%  if task.tab.user.present? %>
<td><%= link_to task.tab.user.name, task.tab.user %></td>
<% else %>
<td>No Tab </td>
<% end %>
<td><%= task.customer.applicant_name if task.customer %><%= task.customer_office.customer.applicant_name if task.customer_office %></td>
<td><%= task.customer.status if task.customer %></td>
</tr>
<% end %>
</table>

app/views/dashboard/_completed_customers.html.erb
	  <p>Completed Customers</p>
	  <table class="table table-condensed table-striped table-bordered">
      <tr>
        <th> Applicant Name </th>
      </tr>
		  <% @completed_customers.each do |task| %>
		  <tr>
			  <td><%= task.applicant_name %> <strong style="float:right;margin-right:50px;"> <%= link_to 'More..', servey_path(task.servey) %>
			  <td style="text-align:center"><%= link_to "Accept", accept_customer_path(task.slug, :customer_id => task.id) %></td>
			  <td style="text-align:center"><%= link_to "Reassign", reassign_customer_path(task.id, :customer_id => task.id) %></td>
		  </tr>
		  <% end %>
	  </table>
    <hr>

app/views/dashboard/_in_progress.html.erb
	  <p>Completed Customers</p>
	  <table class="table table-condensed table-striped table-bordered">
      <tr>
        <th> Applicant Name </th>
      </tr>
		  <% @in_progress_customers.each do |task| %>
		  <tr>
			  <td><%= task.applicant_name %> <strong style="float:right;margin-right:50px;"> <%= link_to 'More..', servey_path(task.servey) %>
		  </tr>
		  <% end %>
	  </table>
    <hr>

app/views/dashboard/_residential_verification.html.erb
<p> Residential Verifications</p>
<table class="table table-condensed table-bordered table-striped">
	<tr>
		<th> Tab Name </th>
		<th> Customer Name  </th>
		<th> Status </th>
	</tr>
		<% @assignments.each do |task| %>
	<tr>
		<%  if task.tab.user.present? %>
		<td><%= link_to task.tab.user.name, task.tab.user %></td>
		<% else %>
		<td>No Tab </td>
		<% end %>
		<td><%= task.customer.applicant_name if task.customer %><%= task.customer_office.customer.applicant_name if task.customer_office %></td>
		<td><%= task.customer.status if task.customer %></td>
	</tr>
	<% end %>
</table>

app/views/dashboard/_sidebar.html.erb
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3" id="sidebar">
            <ul class="nav nav-list bs-docs-sidenav nav-collapse collapse">
                <li class="active">
                   <a href="/"><i class="icon-chevron-right"></i> Dashboard</a>
                </li>
                <li>
                   <a href="calendar.html"><i class="icon-chevron-right"></i> Calendar</a>
                </li>
                <li>
                   <a href="stats.html"><i class="icon-chevron-right"></i> Statistics (Charts)</a>
                </li>
            </ul>
        </div>

app/views/dashboard/_super_user.html.erb
<%= render "completed_customers" %>
<%= render "assigned_tasks" %>

app/views/dashboard/_tab.html.erb
 <b style="font-size:14px; color:green">Welcome ! <%= current_user.name %> <i class="icon-user"></i></b><br>
 <strong style="font-size:18px;color:red"><%= current_user.tab.name if current_user.tab %></strong>
 <hr>

 <p> Assigned Customers </p><hr>

  <table class="table table-striped table-bordered table-condensed" style="width:800px;">

   <tr>
    <th>Residential Verification</th>
    <th> Office Verification </th>
  </tr>

<% if current_user.tab %>
  <tr>
    <td><%= current_user.tab.assignments.joins(:customer).where('assignments.customer_office_id IS NULL and customers.status =? ', 'submitted').count %></td>
    <td><%= current_user.tab.assignments.joins(:customer_office).where('assignments.customer_office_id IS NOT NULL and customer_offices.status =? ', 'pending').count %></td>
  </tr>
<% end %>  
 </table>  
<% if current_user.tab %>
<hr>
  <table class ="table table-striped table-condensed table-bordered">
   <tr>
   <th> Customer Name </th>
   <th> Address </th>
   <th> Action </th>
   </tr>
  <% @tab_user_task.includes(:customer, :user, :tab).includes(:customer_office).each do |tab_task| %>

  <% if tab_task && tab_task.customer && tab_task.customer.status == 'submitted' %>
  <tr>
   <td><%= tab_task.customer.applicant_name %></td>
   <td><%= tab_task.customer.address %></td>
   <% if tab_task.customer %>
   <td><%= link_to "Start Servey", new_servey_path(:user_id => tab_task.user.id, :tab_id => tab_task.tab.id , :customer_id => tab_task.customer.id) %></td>
   <% elsif tab_task.customer_office %>
     <td>Sdr</td>
   <% end %>
   </tr>
  <% end %>

  <% if tab_task && tab_task.customer_office && tab_task.customer_office.customer.status == 'submitted' %>
  <tr>
   <td><%= tab_task.customer_office.customer.applicant_name %></td>
   <td><small><%= tab_task.customer_office.customer.address %></small></td>
   <td><%= link_to "Start Servey", new_servey_path(:user_id => tab_task.user.id, :tab_id => tab_task.tab.id , :customer_id => tab_task.customer_office.customer.id) %></td>
   </tr>
  <% end %>

   <% end %>
  </table>
<% end %>

app/views/dashboard/_tabs_task.html.erb
<table class="table table-condensed table-bordered" style="width:900px;">
<tr>
	<th> Tab Name </th>
	<th> Number of task </th>
	<th style="text-align:center"> Status </th>
</tr>
<% Tab.all.includes(:assignments).each do |t| %>
<tr>
	<td><%= t.name %></td>
	<td><a style = "color:gray">Total : <%= t.assignments.includes(:assignments).count %></a></td>
	    <td>
		 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	     <a style = "color:maron">Pending : &nbsp;&nbsp;<%= pending_task_on_tab(t).count %></a>&nbsp;&nbsp; | 
         <a style = "color:maron">Submitted : &nbsp;&nbsp;<%= submitted_task_on_tab(t).count %></a>&nbsp;&nbsp; | 
	     <a style = "color:maron">In Progress :&nbsp;&nbsp;<%= in_progress_task_on_tab(t).count %></a>&nbsp;&nbsp; |   
	     <a style = "color:maron">verified :&nbsp;&nbsp;<%= verified_task_on_tab(t).count %></a>
	</td>
</tr>
<% end %>
<table>

app/views/dashboard/index.html.erb
<% if logged_in? && current_user.role_name == "super_user" %>
  <%#= render "super_user" %>
  <b><p style="font-size:15px;color:green;text-transform:capitalize;">Welcome, <%= current_user.name %> <i class="icon-user"></i></p></b><hr>

<h5>Completed Verifications</h5>

<table class="table table-condensed table-striped table-bordered">
	<tr>
		<td style="padding-left:20px;">Completed Verification</td>
		<td style="padding-left:20px;">Pending Verification</td>
        <td style="padding-left:20px;">In Progress Verification</td>		
	</tr>
	<tr>
	<% if @completed_customers.present? %>
		<td><h1 style="padding-left:50px;"><%= link_to @completed_customers.count, completed_path %></h1></td>
	<% else %>
		<td><h1> 0 </h1></td>
    <% end %>
	
	<% if @pending_customers.present? %>
		<td><h1 style="padding-left:50px;"><%= link_to @pending_customers.count, pending_path %></h1></td>	
	<% else %>
		<td><h1> 0 </h1></td>		
	<% end %>
    
    <% if @in_progress_customers.present? %>		
        <td><h1 style="padding-left:50px;"><%= link_to @in_progress_customers.count %></h1></td>			
	<% else %>
        <td><h1> 0 </h1></td>		
	<% end %>
	</tr>
</table>
	<hr>

<h5> Assigned Verifications </h5>
<table class="table table-condensed table-striped table-bordered">
	<tr>
		<td style="padding-left:20px;">Residential Verification</td>
        <td style="padding-left:20px;">Office Verification</td>
    </tr>
    <tr>
        <td><h1 style="padding-left:50px;"><%= link_to @assignments.count, residential_verifications_path %></h1></td>
        <td><h1 style="padding-left:50px;"><%= link_to @office_assignments.count, office_verifications_path %></h1></td>
    </tr>
</table>

<% elsif logged_in? && current_user.role_name == "tab_user" %>
  <%= render "tab" %>
<% end %>

app/views/dashboard/residential_verification.html.erb
<p> Residential Verifications</p>
<table class="table table-condensed table-bordered table-striped">
	<tr>
		<th> Tab Name </th>
		<th> Customer Name  </th>
		<th> Status </th>
	</tr>
		<% @assignments.each do |task| %>
	<tr>
		<%  if task.tab.user.present? %>
		<td><%= link_to task.tab.user.name, task.tab.user %></td>
		<% else %>
		<td>No Tab </td>
		<% end %>
		<td><%= task.customer.applicant_name if task.customer %><%= task.customer_office.customer.applicant_name if task.customer_office %></td>
		<td><%= task.customer.status if task.customer %></td>
	</tr>
	<% end %>
</table>