config/routes.rb
Airecel::Application.routes.draw do
  resources :pincodes
  resources :tab_tasks
  #get "accounts/index"
  #get "reports/index"
  resources :serveys, :accounts
  resources :reports
  resources :assignments
  resources :tabs do
    get :autocomplete_pincode_pin_number, :on => :collection
  end

  resources :customers do
   collection do
    post :import
   end
   member do
    get :accept
    post :accpet
    get :reassign
    post :reassign
    get :customer_mapdetail
   end
  end
  resources :users
  resources :sessions , only: [:new,:create,:destroy]
  #match '/residential-verifications',  to: 'assignments#residential_verifications',  via: 'get'
  get "dashboard/residential-verifications" => "assignments#residential_verifications", :as => :residential_verifications
  get "dashboard/office-verifications" => "assignments#office_verifications", :as => :office_verifications

  get "cusomers/completed" => "customers#completed", :as => :completed
  get "cusomers/pending" => "customers#pending", :as => :pending
  get "cusomers/in_progress" => "customers#in_progress", :as => :in_progress
  get "dashboard/index"
  match '/signup',  to: 'users#new',  via: 'get'
  #match '/completed', to: 'appointments#completed', via: 'get'
  match '/login' , to: "sessions#new" , via: "get"
  match '/logout'  ,to: "sessions#destroy" , via: "delete"
  root 'dashboard#index'
end

app/models/customer.rb
class Customer < ActiveRecord::Base

	validates_presence_of:applicant_name, :application_ref_number, :address
	validates_uniqueness_of :application_ref_number

  #validate :valid_date?

  def valid_date?
    if self.date_of_birth.nil?
      errors.add(:date_of_birth, "is missing or invalid")
    end
  end

	extend FriendlyId
	friendly_id :applicant_name, use: :slugged

  #has_one :servey, :dependent => :destroy
  has_one :customer_office
  belongs_to :tab
  belongs_to :customer_type
  has_one :assignment, dependent: :destroy
  has_one :servey, dependent: :destroy

  geocoded_by :full_address
  after_validation :geocode, :if => :address_changed?

  def full_address
   [address, coountry, city, state].compact.join(', ')
  end

	def should_generate_new_friendly_id?
		applicant_name_changed?
	end

 def self.import(file)
	 application_ref_number = 1001
   allowed_attributes = ['application_ref_number','customer_type_id','ageny_name', 'applicant_name', 'address', 'activation_code','dist_code', 'channel_string', 'caf_number', 'landmark', 'date_of_birth', 'pincode', 'contact_number', 'status', 'coountry', 'state', 'city', 'msisdn_number']
   spreadsheet = open_spreadsheet(file)
   header = spreadsheet.row(1)
   (2..spreadsheet.last_row).collect do |i|
    row = Hash[[header,spreadsheet.row(i)].transpose]
    customer = Customer.find_by_id(row["id"]) || new
    customer.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
    customer.msisdn_number = spreadsheet.row(i)[3].to_i
    customer.application_ref_number = spreadsheet.row(i)[1].to_i
    customer.address = spreadsheet.row(i)[5]
    customer.pincode = spreadsheet.row(i)[7].to_i
    customer.dist_code = spreadsheet.row(i)[12].to_i
    if Customer.all.any?
      customer.application_ref_number = Customer.last.application_ref_number.to_i+1
    else
      customer.application_ref_number = application_ref_number.to_i
    end
    customer.save!
     if spreadsheet.row(i)[8].present?
       self.generate_customer_office_detail(customer, spreadsheet, i, row)
     end
     self.assign_customer_to_tab(customer)
   end
 end

  def self.assign_customer_to_tab(customer)
    customer_pincode = Customer.where('id=?', customer.id)
    tab_id = Tab.find_by_pincode(customer_pincode.map(&:pincode))
    if tab_id.present?
      assign_to_tab = Assignment.create!(user_id: 1, tab_id: tab_id.id, customer_id: customer.id)
      assign_to_tab.customer.submit!
      assign_to_tab.save!
    end
  end

  def self.generate_customer_office_detail(customer, spreadsheet, i, row)
		allowed_attributes = ['customer_id', 'office_city', 'office_pincode', 'office_address']
    office = CustomerOffice.new
    office.customer_id = customer.id
    office.office_city = spreadsheet.row(i)[9]
    office.office_pincode = spreadsheet.row(i)[10].to_i
    office.office_address = spreadsheet.row(i)[8]
    office.save!
    customer_pincode = CustomerOffice.where('id=?', office.id)
    tab_id = Tab.find_by_pincode(customer_pincode.map(&:office_pincode))
    if tab_id.present?
      assign_to_tab = Assignment.create!(user_id: 1, tab_id: tab_id.id, customer_office_id: office.id)
      assign_to_tab.save!
    end
  end

  private

  def self.find_tab(tab)
    tab_pincode_to_integer = tab.pincode.to_i
    tab_pincode_number = tab_pincode_to_integer.to_s
    tabname = Tab.find_by_pincode(tab_pincode_number)
    if tabname && !tabname.nil?
      Assignment.create(tab_id: tabname.id, customer_id: tab.id)
    end
  end

  	def self.open_spreadsheet(file)
  		case File.extname(file.original_filename)
  		when '.csv' then Roo::Csv.new(file.path, nil, :ignore)
  		when '.xls' then Roo::Excel.new(file.path, nil, :ignore)
  		when '.xlsx' then Roo::Excelx.new(file.path, nil, :ignore)
  		else raise "Pfiiflichopf!!"
  		end
  	end


#	validate :correct_content_type, :message => ", Only EXCEL files are allowed."
#
#
#	def correct_content_type
#		acceptable_types = ["application/pdf","application/vnd.ms-excel",
#		           "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
#		           "application/msword",
#		           "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
#		           "text/plain"]
#		acceptable_types.include? uploaded_file.content_type.chomp
#	end

include Workflow

workflow_column :status

  workflow do

    state :pending do
      event :submit, :transitions_to => :submitted
    end

    state :submitted do
      event :complete, :transitions_to => :completed
    end

    state :completed do
      event :accept, :transitions_to => :verified
    end

    state :verified do
      event :re_assign, :transitions_to => :pending
    end

end

end

app/models/customer_type.rb
class CustomerType < ActiveRecord::Base
	has_many :customers
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :login_required
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  #load_and_authorize_resource
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.order("created_at DESC").includes(:customer_type, :customer_office)
    @customer = Customer.new
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
   @new_assignments = Assignment.new
  end

  # GET /customers/new
  def new
    @customer = Customer.new
     if Customer.any?
       @new_no = Customer.last.application_ref_number.to_i
       @final_no = (@new_no+1)
     else
       @final_no = 1001
       @date = Time.now
       @current_date = @date.strftime("%B %d, %Y")
     end
  end


 def customer_mapdetail
  @customer = Customer.find(params[:customer_id])
 end



  # GET /customers/1/edit
  def edit
   #@customer = Customer.find(params[:id])
   @final_no = @customer.application_ref_number
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
     if @customer.application_ref_number==""
       @customer.application_ref_number = Customer.last.application_ref_number+1
     end
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
   Customer.import params[:file]
   redirect_to customers_path, notice: "Imported!!"
  end

  def accept
   @customer = Customer.find(params[:customer_id])
   @customer.accept!
     redirect_to @customer, notice: 'Customer was successfully updated.'
  end


  def reassign
   @customer = Customer.find(params[:customer_id])
   @customer.re_assign!
     redirect_to @customer, notice: 'Customer was successfully updated.'
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  def assignments
   @customer = Customer.find(params[:customer_id])
  end

  def completed 
   @completed_customers = Customer.where(status: "verified")
  end

  def pending
   @pending_customers = Customer.where(status: "submitted")
  end

  def in_progress
   @in_progress_customers = Customer.where(status: "completed")   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.friendly.find(params[:id])
      @hash = Gmaps4rails.build_markers(@customer) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end


    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:application_ref_number,:office_address, :city_office, :office_pincode, :msisdn_number, :ageny_name, :applicant_name, :address, :activation_code, :dist_code, :channel_string, :caf_number, :landmark, :date_of_birth, :pincode, :contact_number, :status, :coountry, :state, :city)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= nested_form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <!--<h2><%#= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>-->
      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="row">
  <div class="field">
    <%= f.label :application_ref_number %>
    <% if @customer.blank? %>
      <b><%= f.text_field :application_ref_number, :class=>"form-control", :value=> @final_no %></b>
    <% else %>
      <b><%= f.text_field :application_ref_number, :class=>"form-control", :value=> @final_no %></b>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :ageny_name %>
    <%= f.text_field :ageny_name, :class=>"form-control" , :value => "Scorpeo Private Limited" %>
  </div>

  <div class="field">
    <%= f.label :applicant_name %>
    <%= f.text_field :applicant_name, :class=>"form-control" %>
  </div></div>

  <div class="row">
  <div class="field">
    <%= f.label :billing_address %>
    <%= f.text_area :address, :class=>"form-control" %>
  </div></div>

  <div class="row">
  <div class="field">
    <%= f.label :landmark %>
    <%= f.text_field :landmark, :class=>"form-control" %>
  </div>
    <div class="field">
    <%= f.label :contact_number %>
    <%= f.text_field :contact_number, :class=>"form-control" %>
  </div>
  </div>

  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth, :class=>"form-control", :start_year => 1990,
                      :prompt => { :day => 'Select day', :month => 'Select month', :year => 'Select year' }  %>
  </div><br><br>
 <div class="row">
  <div class="field">
    <%= f.label :Caf_Number %>
    <%= f.text_field :caf_number, :class=>"form-control", :value=> @final_no %>
  </div>
  <div class="field">
    <%= f.label :country %>
    <b><%= f.text_field :coountry, :class=>"form-control", :value => "India" %></b>
  </div>
  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state, :class=>"form-control", :value => "Maharashtra" %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city, :class=>"form-control", :value => "Mumbai" %>
  </div>
    <div class="field">
    <%= f.label :Zipcode %>
    <%= f.text_field :pincode, :class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label 'Activation Status' %>
    <%= f.text_field :activation_code, :class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label 'Distributor Code' %>
    <%= f.text_field :dist_code, :class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :Channel %>
    <%= f.text_field :channel_string, :class=>"form-control" %>
  </div>
  </div>
<hr>
<style>
input, textarea{ height: auto;
    width: 552px;}
</style>
<div class="office" style="padding:20px;background:#F0F8FF;">

<h4> Office Details if any ? </h4><hr>
  <%= f.fields_for :customer_office do |co| %>
 <div class="row">

    <div class="field">
      <%= co.label 'Office Address' %>
      <%= co.text_area :office_address, :class=>"form-control" %>
    </div>
  </div>

 <div class="row">
  <div class="field">
    <%= co.label 'Office City' %>
    <%= co.text_field :city_office, :class=>"form-control" %>
  </div>

  <div class="field">
    <%= co.label 'Office Pincode' %>
    <%= co.text_field :office_pincode, :class=>"form-control" %>
  </div>
 </div>
  <% end %>

</div>

  <br><br>
  <div class="actions">
    <%= f.submit :class=>"btn btn-info" %> <%= link_to 'Back', customers_path, :class=>"btn" %>
  </div>
<% end %>

app/views/customers/completed.html.erb
<%= render "dashboard/completed_customers" %>

app/views/customers/customer_mapdetail.html.erb
<%= %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

app/views/customers/in_progress.html.erb
<%= render "dashboard/in_progress" %>

app/views/customers/index.html.erb
<style>
.dataTables_wrapper{width:auto;}
label {
    font-size: 13px;
    padding: 0 40px 5px;
}
</style>
<strong style="float:right"> <%= link_to "Add Customer", new_customer_path, :class=>"btn btn-info" %> </strong>
<strong>Import Customers</strong>
<table><%= form_tag import_customers_path, multipart: true do %>
    <tr><td><%= file_field_tag :file %><br></td></tr>
    <tr><td><%= submit_tag "Upload Customers", class: 'btn btn-danger' %></td></tr>
<% end %></table>
<hr>

<table id="customers" class = "table table-condensed table-bordered table-striped">
  <thead>
    <tr>
      <th>Sr.no.</th>
      <th>Customer Type</th>
      <th>Reference number</th>
      <th>CAF Number</th>
      <th>MSISDN Number</th>
      <th>Applicant name</th>
      <th>Pincode </th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= customer.customer_type.name if customer.customer_type %></td>
        <td><%= customer.application_ref_number %></td>
        <td><%= customer.caf_number %></td>
        <td><%= customer.msisdn_number %></td>
        <td><%= link_to customer.applicant_name, customer %></td>
        <td><%= customer.pincode %></td>
        <td><% if customer.status == 'verified' %>
        <span class="badge"><%= customer.status %></span></td>
         <% elsif customer.status == 'completed' %>
        <span class="badge"><%= customer.status %></span></td>
         <% elsif customer.status == 'submitted' %>
        <span class="badge"><%= customer.status %></span></td>
         <% else %>
        <span class="badge"><%= customer.status %></span></td>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br>

app/views/customers/new.html.erb
<%= render 'form' %>

app/views/customers/pending.html.erb
<p>Pending Verifications</p>
	<table class="table table-condensed table-striped table-bordered" style="width:300px;">
		<tr>
			<th> Applicant Name </th>
		</tr>
	<% @pending_customers.each do |task| %>
		<tr>
			<td><%= task.applicant_name %></td>
		</tr>
	<% end %>
	</table>
<hr>

app/views/customers/show.html.erb
<style>
 #sidebar {
	width: 300px;
	float: right;
	margin-right: 5px;
	padding-left: 40px;
  padding-bottom: 20px;
}


 .dk_toggle{  padding:4px 4px 4px 4px;width:250px;height:27px;}
 .dk_container{margin-bottom:0px;}

.dk_fouc select{
	background-color: #666;
	border: medium none;
	border-radius: 5px;
	color: #FFFFFF;
	font-size: 12px;
	height: 30px;
	padding: 6px;
	position: relative;
	top: 0;
	visibility: visible;
	float: left;
	margin-right: 10px;
	outline:none;
}

.dk_fouc select option{
	border:none;
	margin-top:10px;
	background-color: #666;
}
.btn.btn-primary { border:none;}
</style>

<h5><i class="icon-edit"></i> <%= link_to 'Edit', edit_customer_path(@customer) %> |
<i class=" icon-remove-sign"></i> <%= link_to 'Destroy', @customer, method: :delete, data: { confirm: 'Are you sure?' } %> |
<i class="icon-th"></i> <%= link_to 'View All', customers_path %></h5>
<% if @customer.status == 'pending' %>
  <h3> <span class="btn btn-hg btn-warning"><%= @customer.status %></span></h3>
<% elsif @customer.status == 'submitted' %>
  <h3> <span class="label label-info"><%= @customer.status %></span></h3>
<% elsif @customer.status == 'completed' %>
  <h3> <span class="btn btn-hg btn-primary"><%= @customer.status %></span></h3><br><br><br><br>
  <p>
    <%= link_to "Accept", accept_customer_path(:customer_id => @customer.id), :class=> "label label-success" %>
    <%#= link_to "Reassign", reassign_customer_path(:customer_id => @customer.id), :class=> "label label-danger" %>
  </td>
  <% else %>
  <h3> <span class="btn btn-hg btn-primary"><%= @customer.status %></span></h3>
<% end %>
<br><br>

<style>
 .dropdown{ border: medium none;
    border-radius: 4px 4px 4px 4px;
    font-size: 12px;
    font-weight: normal;
    line-height: 1.4;
    padding: 9px 10px;
    transition: all 0.25s linear 0s;
    background:#1ABC9C;
    color:#fff;}
</style>

<% if logged_in? && current_user.role_name=="super_user" &&  @customer.status=="pending" %>

   <%= form_for(@new_assignments) do |f| %>
    <%= f.hidden_field :customer_id , :value => @customer.id %>
    <%= f.hidden_field :user_id , :value => current_user.id %>
    <%= select_tag "assignment[tab_id]", options_for_select(User.includes(:tab).where('users.role_name!=?', 'super_user').collect {|r| [r.name, r.tab.id] }) %>
    <span class="dropdown-arrow"></span>
   <%= f.submit "Send for verification", :class=>"btn btn-primary btn-small" %>
 <% end %>
<% else %>

<% if @customer.status=="submitted" %>
<br>
    <% if @customer.status=='submitted' %>
     <!--<td><span class="label label-warning">Submitted to Tab User </span></td></tr><br>-->
		 <b style="font-size:15px;" class="label label-warning">
		   The customer has been send for verification. this has been assigned to  &nbsp;&nbsp;
		   <%= @customer.assignment.tab.user.name if @customer.assignment.tab.user %></b>
    <% end %>


<% end %>
<% end %>
<br><br><br>

<div id ="sidebar">

<% if @customer.servey && @customer.servey.document_photos.present? %>
<p> Documents Submitted by customers </p><hr>
<% @customer.servey.document_photos.each do |doc| %>
 <%= image_tag doc.photo.url(:small) %><hr>
<% end %>
<% end %>
</div>

<h3 style="color:gray"><%= @customer.applicant_name %></h3>


<table class="table table-condensed table-bordered table-striped">
<tr><td>Application ref number:</td>
    <td><%= @customer.application_ref_number %></td></tr>

<tr><td>
  Address:</td>
  <td><%= @customer.address %>
</td><tr>

<tr><td>
  Pincode:</td>
  <td><%= @customer.pincode %>
</td><tr>

<tr><td>
  City:</td>
  <td><%= @customer.city %>
</td><tr>
</table>

<% if @customer.customer_office %>
<h3 style="color:gray">Office Detail</h3>
<table>
  <tr>
  <td><%= @customer.customer_office.office_address %><br>
  <%= @customer.customer_office.office_pincode %><br>
  <%= @customer.customer_office.status %></td>  
</tr>
</table>
<% end %>

<hr>
<% if @customer.servey  %>
<p style = "font-size:15px"> Servey Info </p>
<p style="padding:2px 2px 2px 7px;background:blue;color:white;width:650px">Servey Done By : <%= @customer.servey.tab.user.name %>
| Created By :<%= @customer.servey.user.name %></p>
<p>
Final Recomendation :
<% if @customer.servey.remark_team_leader == 'Positive' %>
  <b style="padding:0px 5px 0px 5px;font-weight:100px;color:white;background:green">
   <%= @customer.servey.remark_team_leader %></b></p>
 <% else %>
   <b style="background:red">
   <%= @customer.servey.remark_team_leader %></b></p>
 <% end %>
<hr>

<table class="table" style="width:500px;">
<th>Detail</th>

<tr>
 <td>Email :</td>
 <td> <%= @customer.servey.email %></td></tr>
</tr>
<tr>
	<td>Bill PLan : </td>
	<td><%= @customer.servey.bill_plan %></td>
</tr>
<tr>
 <td>billing address :</td>
 <td><%= @customer.servey.billing_address %></td>
</tr>

<td>Address Verified :</td><td> <%= @customer.servey.address_verified %></td></tr>

<td>Alternate Number : </td>
<td><%= @customer.servey.alternate_number %></td>
</tr>
<tr>
<td>Have Your Applied Before for this connection?:</td>
<td> <%= @customer.servey.applied_before %></td>
</tr>
<tr>
<td>Sim Recieved : </td>
<td><%= @customer.servey.sim_recieved %></td>
</tr>
<tr>
<td>Sim NUmber:</td>
<td> <%= @customer.servey.sim_number %></td>
</tr>
<td>postpaid connection first time ? :</td><td> <%= @customer.servey.postpaid_connection_first_time %></td></tr>
<td>Residence Type :</td><td> <%= @customer.servey.type_of_residence %></td></tr>

<td>Locality :</td><td> <%= @customer.servey.locality %></td></tr>

<td>Residence status : </td><td><%= @customer.servey.type_of_stay %></td></tr>

<td>years to stay :</td><td> <%= @customer.servey.years_of_stay %></td></tr>

<td>Occupation :</td><td> <%= @customer.servey.occupation %></td></tr>

<td>Type Of Work : </td><td><%= @customer.servey.type_of_work %></td></tr>

<td>Organisation Type :</td><td> <%= @customer.servey.type_of_organisation %></td></tr>

<td>Documentation : </td><td><%= @customer.servey.documentation %></td></tr>

<td>Person Met  : </td><td><%= @customer.servey.person_met %></td></tr>

<td>Visit Number : </td><td><%= @customer.servey.visit_number %></td></tr>

<td>Network	: </td><td><%= @customer.servey.network %></td></tr>
<td>Av Result : </td><td><%= @customer.servey.av_result %></td></tr>
<td>Av Supervisor name : </td><td><%= @customer.servey.team_leader_name %></td></tr>
<td>Date Of Visit : </td><td><%= @customer.servey.date_of_visit %></td></tr>
<td>Remark Tab : </td><td><%= @customer.servey.remark_tab %></td></tr>
<td>Av Supervisor Remark : </td><td><%= @customer.servey.remark_team_leader %></td></tr>
</table>
<% end %>

<hr>
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
    });
</script>
<br><br>