config/routes.rb
Airecel::Application.routes.draw do
  resources :pincodes
  resources :tab_tasks
  #get "accounts/index"
  #get "reports/index"
  resources :serveys, :accounts
  resources :reports
  resources :assignments
  resources :tabs do
    get :autocomplete_pincode_pin_number, :on => :collection
  end

  resources :customers do
   collection do
    post :import
   end
   member do
    get :accept
    post :accpet
    get :reassign
    post :reassign
    get :customer_mapdetail
   end
  end
  resources :users
  resources :sessions , only: [:new,:create,:destroy]
  #match '/residential-verifications',  to: 'assignments#residential_verifications',  via: 'get'
  get "dashboard/residential-verifications" => "assignments#residential_verifications", :as => :residential_verifications
  get "dashboard/office-verifications" => "assignments#office_verifications", :as => :office_verifications

  get "cusomers/completed" => "customers#completed", :as => :completed
  get "cusomers/pending" => "customers#pending", :as => :pending
  get "cusomers/in_progress" => "customers#in_progress", :as => :in_progress
  get "dashboard/index"
  match '/signup',  to: 'users#new',  via: 'get'
  #match '/completed', to: 'appointments#completed', via: 'get'
  match '/login' , to: "sessions#new" , via: "get"
  match '/logout'  ,to: "sessions#destroy" , via: "delete"
  root 'dashboard#index'
end

app/models/servey.rb
class Servey < ActiveRecord::Base
 belongs_to :customer
 belongs_to :tab
 belongs_to :user
 has_many :document_photos
 accepts_nested_attributes_for :document_photos#, reject_if: proc { |attributes| attributes['servey_id'].blank? }

 before_save :set_image

  def set_image
    if self.signature_image.present?
      require "base64"
			encoded_image = signature_image.split(",")[1]
			decoded_image = Base64.decode64(encoded_image)
			File.open(Rails.root.to_s + "/app/assets/images/#{self.customer.applicant_name}_signature.png", "wb") { |f| f.write(decoded_image) }
			self.signature_image = "#{self.customer.applicant_name}_signature.png"
    end
  end
end

app/controllers/serveys_controller.rb
class ServeysController < ApplicationController
  before_action :set_servey, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?
  # GET /serveys
  # GET /serveys.json
  def index
    unless current_user.admin?
    @serveys = Servey.where(tab_id: current_user.tab.id)
    else
    @serveys = Servey.all
    end
  end

  # GET /serveys/1
  # GET /serveys/1.json
  def show
  end

  # GET /serveys/new
  def new
    @servey = Servey.new
    @id = Customer.find(params[:customer_id])
  end

  # GET /serveys/1/edit
  def edit
      @id = Customer.find(params[:id])
  end

  # POST /serveys
  # POST /serveys.json
  def create
    @servey = Servey.new(servey_params)

    respond_to do |format|
      if @servey.save
        @servey.customer.complete!
        format.html { redirect_to root_url, notice: 'Servey was successfully created.' }
        format.json { render action: 'show', status: :created, location: @servey }
      else
        format.html { render action: 'new' }
        format.json { render json: @servey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /serveys/1
  # PATCH/PUT /serveys/1.json
  def update
    respond_to do |format|
      if @servey.update(servey_params)
        format.html { redirect_to @servey, notice: 'Servey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @servey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /serveys/1
  # DELETE /serveys/1.json
  def destroy
    @servey.destroy
    respond_to do |format|
      format.html { redirect_to serveys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servey
      @servey = Servey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servey_params
      params.require(:servey).permit(:customer_id, :tab_id, :user_id, :alternate_number, :date_of_birth, :bill_plan,
                                     :email, :billing_address_correction, :new_billing_address, :office_address_correction,
                                     :new_office_address, :applied_before, :sim_recieved, :sim_number,
                                     :postpaid_connection_first_time, :address_verified, :locality, :type_of_locality,
                                     :type_of_residence, :type_of_stay, :years_of_stay, :occupation, :type_of_work,
                                     :type_of_organisation, :documentation, :person_met, :name_person_met, :visit_number,
                                     :network, :av_result, :agency_name, :team_leader_name, :date_of_visit, :remark_tab,
                                     :remark_team_leader, :billing_address, :signature_image,
                                     document_photos_attributes: [:servey_id, :photo, :_destroy])
    end
end

app/helpers/serveys_helper.rb
module ServeysHelper
end

app/views/serveys/_form.html.erb
<%= javascript_include_tag 'app.js', 'signature_pad.js' %>
<%= nested_form_for @servey do |f| %>
  <% if @servey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@servey.errors.count, "error") %> prohibited this servey from being saved:</h2>

      <ul>
      <% @servey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.fields_for :document_photos do |photo| %>
		<%= photo.file_field :photo %>
		<%= photo.link_to_remove "Remove this Document" %>
	<% end %>

<p><%= f.link_to_add "Add a Document", :document_photos %></p>
  <div class="field">
    <%= f.hidden_field :customer_id, :value => params[:customer_id] %>
  </div>
  <div class="field">
    <%= f.hidden_field :tab_id, :value => params[:tab_id] %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => params[:user_id] %>
  </div>

<hr>
  <p style="color:red"> C.A.F. Number : <u><%= (@id.created_at).to_date %>-<%= @id.application_ref_number %></u></p>

  <div class="field">
    <b><%= f.label :"alternate Number:" %></b>
    <%= f.text_field :alternate_number %>
  </div>
  <div class="field">
    <%= f.label :ease_of_location %>
   <div class="controls">
       Easy <input id="servey_address_confirmed" name="servey[ease_of_location]" type="radio" value="Easy" />
       Difficult <input id="servey_address_confirmed" name="servey[ease_of_location]" type="radio" value="Difficult" />
       untraceable <input id="servey_address_confirmed" name="servey[ease_of_location]" type="radio" value="Untraceable" />
    </div>
  </div><br>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :Bill_Plan %>
    <%= f.text_field :bill_plan %>
  </div>

  <div class="field">
    <%= f.label :Billing_Address %>
    <%= f.text_field :billing_address %>
  </div>

  <div class="field">
    <%= f.label :Billing_Address_Correction %>
    <%= f.radio_button :billing_address_correction, "1" %> Yes
    <%= f.radio_button :billing_address_correction, "0" %> No
  </div><br>

  <div class="field">
    <%= f.label :New_Billing_Address %>
    <%= f.text_field :new_billing_address %>
  </div>

  <div class="field">
    <%= f.label :Office_Address_Correction %>
    <%= f.radio_button :office_address_correction, "1" %> Yes
    <%= f.radio_button :office_address_correction, "0" %> No
  </div><br>

  <div class="field">
    <%= f.label :New_Office_Address %>
    <%= f.text_field :new_office_address %>
  </div><hr>

  <div class="field">
    <%= f.label :Have_You_Applied_For_This_Connection_Before? %>
    <%= f.radio_button :applied_before, "1" %> Yes
    <%= f.radio_button :applied_before, "0" %> No
  </div><hr>

  <div class="field">
    <%= f.label :Sim_Recieved %>
    <%= f.radio_button :sim_recieved, "1" %> Yes
    <%= f.radio_button :sim_recieved, "0" %> No
  </div><hr>
  <div class="field">
    <%= f.label :Sim_Number %>
    <%= f.text_field :sim_number %>
  </div><hr>

  <div class="field">
    <p><%= f.label :PostpaidConnectionFirstTime %></p>
      <%= f.radio_button :postpaid_connection_first_time, "1" %> Yes
      <%= f.radio_button :postpaid_connection_first_time, "0" %> No
  </div>
<hr>
  <div class="field">
    <p><%= f.label :AddressVerified %></p>
       <%= f.radio_button :address_verified, "1" %> Yes
       <%= f.radio_button :address_verified, "0" %> No
  </div><hr>

  <div class="field">
    <p><%= f.label :Locality %></p>
    <%#= f.text_field :residence_type %>
      <label class="checkbox controls">
         <input id="bill_payer" name="servey[locality]" type="checkbox" value="Bunglow" /> Bunglow
      </label>
      <label class="checkbox controls">
         <input id="bill_payer" name="servey[locality]" type="checkbox" value="Flat" /> Flat
      </label>

      <label class="checkbox controls">
         <input id="bill_payer" name="servey[locality]" type="checkbox" value="Chawl" /> Chawl
      </label>
  </div><hr>

  <div class="field">
    <p><%= f.label :Type_Of_Residence %></p>
      <label class="checkbox controls">
         <input id="bill_payer" name="servey[type_of_residence]" type="checkbox" value="Owned" /> Owned
      </label>

      <label class="checkbox controls">
         <input id="bill_payer" name="servey[type_of_residence]" type="checkbox" value="Rented" /> Rented
      </label>
  </div><hr>
  <div class="field">
    <p><%= f.label :TypeOfStay %></p>
      <label class="checkbox controls">
         <input id="bill_payer" name="servey[type_of_stay]" type="checkbox" value="Owned" /> Owned
      </label>

      <label class="checkbox controls">
         <input id="bill_payer" name="servey[type_of_stay]" type="checkbox" value="Rented" /> Rented
      </label>
  </div>
  <div class="field">
    <%= f.label :YearsToStay %>
    <%= f.number_field :years_of_stay %>
  </div>

  <div class="field">
    <%= f.label :Occupation %>
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :TypeOfWork %>
    <%= f.text_field :type_of_work %>
  </div>
  <div class="field">
    <%= f.label :OrganisationType %>
    <%= f.text_field :type_of_organisation %>
  </div>

  <div class="field">
    <%= f.label :DocumentsShown %>
    <%= f.text_field :documentation %>
  </div>

  <div class="field">
    <%= f.label :person_met %>
    <%= f.text_field :person_met %>
  </div>

  <div class="field">
    <%= f.label :NameOfPesonMet %>
    <%= f.text_field :name_person_met %>
  </div>
  <div class="field">
    <%= f.label :VisitNumber %>
    <%= f.number_field :visit_number %>
  </div>
  <div class="field">
    <%= f.label :Network %>
    <%= f.text_field :network %>

    <% if controller.action_name == 'new' %>
<p onselectstart="return false">
  <a id="github" href="https://github.com/szimek/signature_pad">
  </a>

  <div id="signature-pad" class="m-signature-pad" style="width:500px;">
    <div class="m-signature-pad--body" style="border:1px solid silver;">
      <canvas width="500" height="480"></canvas>
    </div>
    <div class="m-signature-pad--footer">
      <div class="description"></div>
       <a href="javascript:void(0)" data-action="clear">Sign Again</a>
       <a href="javascript:void(0)" data-action="save"> Save Signature </a>
      <!--<button class="button clear" data-action="clear">Clear</button>
      <button class="button save" data-action="save">Save</button>-->
    </div>
  </div>
</p>
  <div class="field">
    <%= f.hidden_field :signature_image %>
  </div>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :AvResult %>
    <%= f.text_field :av_result %>
  </div>
  <%= f.hidden_field :date_of_visit, :value => Date.today %>
  <div class="field">
    <%= f.label :TabRemark %>
    <%= f.text_field :remark_tab %>
  </div>
  <div class="field">
    <%= f.label :RemarkTeamLeader %>
    <%= f.text_field :remark_team_leader %>
  </div>
  <div class="actions">
    <%= f.submit :class=> "btn btn-primary", :id => "create_survey", "data-action" => "d" %>
  </div>
<% end %>

app/views/serveys/edit.html.erb
<h1>Editing servey</h1>

<%= render 'form' %>

<%= link_to 'Show', @servey %> |
<%= link_to 'Back', serveys_path %>

app/views/serveys/index.html.erb
<table id="serveys" class = "table table-condensed table-bordered table-striped">
  <thead>
    <tr>
      <th>Customer</th>
      <th>Servey Done By</th>
      <th>Assigned By</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @serveys.each do |servey| %>
      <tr>
        <td><%= servey.customer.applicant_name %></td>
        <td><%= servey.tab.user.name %></td>
        <td><%= servey.user.name %></td>
        <td><%= servey.customer.status %></td>
        <td><%= link_to 'Show', servey %></td>
        <td><%= link_to 'Edit', edit_servey_path(servey) %></td>
        <td><%= link_to 'Destroy', servey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Servey', new_servey_path, :class => "btn btn-primary" %>

app/views/serveys/new.html.erb
<b>New servey</b>

<%= render 'form' %>

<%= link_to 'Back', serveys_path %>

app/views/serveys/show.html.erb
<style>
 #main_content{float:left;width:700px;border-right:1px solid black;padding-right:35px;}
 #sidebar {
	height: 300px;
	width: 400px;
	float: right;
	margin-right: 5px;
	padding: 5px 0 0 5px;
}
</style>

<div id = "actions">
<p style="margin-top:-20px;">
<%= link_to 'Edit Servey', edit_servey_path(@servey) %> |
<%= link_to 'View all Servey', serveys_path %>
<b style="margin-left:450px;">
 <%#= link_to "accept", accept_customer_path(@servey.customer.slug, :customer_id => @servey.customer.id) %></b></p>
</div><hr>

<div id="sidebar">
<h4><b>List Of Documents</b></h4>
<% @servey.document_photos.each do |photo| %>
  <%#= link_to image_tag photo.photo.url(:small) %>
  <%= link_to "Download", photo.photo.url %>
<% end %><hr>
<p> Signature</p>
<%= image_tag("#{@servey.signature_image}") %>
</div>

<div id="main_content">
<table class="table table-striped table-bordered table-condensed">
<tr>
  <td><strong>Name Of the Customer:</strong>
  <td><%= @servey.customer.applicant_name %></td>
</tr>

<tr>
  <td><strong>Name of the Tab User who completed the Servey:</strong>
  <td><%= @servey.tab.user.name %></td>
</tr>

<tr>
  <td><strong>Assigned by :</strong>
  <td><%= @servey.user.name %></td>
</tr>

<tr>
  <td><strong>Address Confirmed:</strong>
  <td><%= @servey.address_verified %></td>
</tr>

<tr>
  <td><strong>Email:</strong>
  <td><%= @servey.email %></td>
</tr>

<tr>
  <td><strong>Sim received:</strong>
  <td><%= @servey.sim_recieved %></td>
</tr>

<tr>
  <td><strong>Sim number:</strong>
  <td><%= @servey.sim_number %></td>
</tr>

<tr>
  <td><strong>Billing Address:</strong>
  <td><%= @servey.billing_address %></td>
</tr>

<tr>
  <td><strong>Applied Before?</strong>
  <td><%= @servey.applied_before %></td>
</tr>

<tr>
  <td><strong>First Time Postpaid Connection:</strong>
  <td><%= @servey.postpaid_connection_first_time %></td>
</tr>

<tr>
  <td><strong>Locality:</strong>
  <td><%= @servey.locality %></td>
</tr>

<tr>
  <td><strong>Type Of Residence:</strong>
  <td><%= @servey.type_of_residence %></td>
</tr>

<tr>
  <td><strong>Type Of Stay:</strong>
  <td><%= @servey.type_of_stay %></td>
</tr>
<tr>
  <td><strong>Years Of Stay:</strong>
  <td><%= @servey.years_of_stay %></td>
</tr>
<tr>
  <td><strong>Occupation:</strong>
  <td><%= @servey.occupation %></td>
</tr>
<tr>
  <td><strong>Type Of Work:</strong>
  <td><%= @servey.type_of_work %></td>
</tr>
<tr>
  <td><strong>Organisation Type:</strong>
  <td><%= @servey.type_of_organisation %></td>
</tr>
<tr>
  <td><strong>Documents Shown:</strong>
  <td><%= @servey.documentation %></td>
</tr>
<tr>
  <td><strong>Person Met:</strong>
  <td><%= @servey.person_met %></td>
</tr>

<tr>
  <td><strong>Name Of  Peson Met:</strong>
  <td><%= @servey.name_person_met %></td>
</tr>

<tr>
  <td><strong>Visit Number:</strong>
  <td><%= @servey.visit_number %></td>
</tr>

<tr>
  <td><strong>Network:</strong>
  <td><%= @servey.network %></td>
</tr>

<tr>
  <td><strong>Av Result:</strong>
  <td><%= @servey.av_result %></td>
</tr>

<tr>
  <td><strong>Team Leader Name:</strong>
  <td><%= @servey.team_leader_name %></td>
</tr>

<tr>
  <td><strong>Date Of Visit:</strong>
  <td><%= @servey.date_of_visit %></td>
</tr>

<tr>
  <td><strong>Tab Remark:</strong>
  <td><%= @servey.remark_tab %></td>
</tr>

<tr>
  <td><strong>Remark Tab Leader:</strong>
  <td><%= @servey.remark_team_leader %></td>
</tr>
</div>