config/routes.rb
Airecel::Application.routes.draw do
  resources :pincodes
  resources :tab_tasks
  #get "accounts/index"
  #get "reports/index"
  resources :serveys, :accounts
  resources :reports
  resources :assignments
  resources :tabs do
    get :autocomplete_pincode_pin_number, :on => :collection
  end

  resources :customers do
   collection do
    post :import
   end
   member do
    get :accept
    post :accpet
    get :reassign
    post :reassign
    get :customer_mapdetail
   end
  end
  resources :users
  resources :sessions , only: [:new,:create,:destroy]
  #match '/residential-verifications',  to: 'assignments#residential_verifications',  via: 'get'
  get "dashboard/residential-verifications" => "assignments#residential_verifications", :as => :residential_verifications
  get "dashboard/office-verifications" => "assignments#office_verifications", :as => :office_verifications

  get "cusomers/completed" => "customers#completed", :as => :completed
  get "cusomers/pending" => "customers#pending", :as => :pending
  get "cusomers/in_progress" => "customers#in_progress", :as => :in_progress
  get "dashboard/index"
  match '/signup',  to: 'users#new',  via: 'get'
  #match '/completed', to: 'appointments#completed', via: 'get'
  match '/login' , to: "sessions#new" , via: "get"
  match '/logout'  ,to: "sessions#destroy" , via: "delete"
  root 'dashboard#index'
end

app/helpers/layout_helper.rb
module LayoutHelper

def copyright_notice_year_range(start_year)
  # In case the input was not a number (nil.to_i will return a 0)
  start_year = start_year.to_i

  # Get the current year from the system
  current_year = Time.new.year

  # When the current year is more recent than the start year, return a string 
  # of a range (e.g., 2010 - 2012). Alternatively, as long as the start year 
  # is reasonable, return it as a string. Otherwise, return the current year 
  # from the system.
  if current_year > start_year && start_year > 2000
    "#{start_year} - #{current_year}"
  elsif start_year > 2000
    "#{start_year}"
  else
    "#{current_year}"
  end
end
end

app/views/layouts/_header.html.erb
<% if signed_in? %>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">Admin Panel</a>
                    <% if signed_in? %>
                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-user"></i> <%= current_user.email%> <i class="caret"></i>
                                </a>
                                <ul class="dropdown-menu">
<!--                                     <li>
                                        <a tabindex="-1" href="#">Profile</a>
                                    </li>
                                    <li class="divider"></li>
 -->                                    <li>
                                        <a tabindex="-1" href="login.html"><%= link_to "Logout", destroy_user_session_path, method: :delete %></a>
                                    </li>
                                </ul>
                            </li>
                        <% else %>
                        <% end %>

                        </ul>
                        <ul class="nav">
                            <li class="active">
                                <a href="#">Dashboard</a>
                            </li>
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Settings <b class="caret"></b>

                                </a>
                                <ul class="dropdown-menu" id="menu1">
                                    <li>
                                        <a href="#">Tools <i class="icon-arrow-right"></i>

                                        </a>
                                        <ul class="dropdown-menu sub-menu">
                                            <li>
                                                <a href="#">Reports</a>
                                            </li>
                                            <li>
                                                <a href="#">Logs</a>
                                            </li>
                                            <li>
                                                <a href="#">Errors</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="#">SEO Settings</a>
                                    </li>
                                    <li>
                                        <a href="#">Other Link</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">Other Link</a>
                                    </li>
                                    <li>
                                        <a href="#">Other Link</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Content <i class="caret"></i>

                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a tabindex="-1" href="#">Blog</a>
                                    </li>
                                    <li>
                                        <a tabindex="-1" href="#">News</a>
                                    </li>
                                    <li>
                                        <a tabindex="-1" href="#">Custom Pages</a>
                                    </li>
                                    <li>
                                        <a tabindex="-1" href="#">Calendar</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a tabindex="-1" href="#">FAQ</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Users <i class="caret"></i>

                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a tabindex="-1" href="#">User List</a>
                                    </li>
                                    <li>
                                        <a tabindex="-1" href="#">Search</a>
                                    </li>
                                    <li>
                                        <a tabindex="-1" href="#">Permissions</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span3" id="sidebar">
                    <ul class="nav nav-list bs-docs-sidenav nav-collapse collapse">
                        <li class="active">
                            <a href="index.html"><i class="icon-chevron-right"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="calendar.html"><i class="icon-chevron-right"></i> Calendar</a>
                        </li>
                        <li>
                            <a href="stats.html"><i class="icon-chevron-right"></i> Statistics (Charts)</a>
                        </li>
                        <li>
                            <a href="form.html"><i class="icon-chevron-right"></i> Forms</a>
                        </li>
                        <li>
                            <a href="tables.html"><i class="icon-chevron-right"></i> Tables</a>
                        </li>
                        <li>
                            <a href="buttons.html"><i class="icon-chevron-right"></i> Buttons & Icons</a>
                        </li>
                        <li>
                            <a href="editors.html"><i class="icon-chevron-right"></i> WYSIWYG Editors</a>
                        </li>
                        <li>
                            <a href="interface.html"><i class="icon-chevron-right"></i> UI & Interface</a>
                        </li>
                        <li>
                            <a href="#"><span class="badge badge-success pull-right">731</span> Orders</a>
                        </li>
                        <li>
                            <a href="#"><span class="badge badge-success pull-right">812</span> Invoices</a>
                        </li>
                        <li>
                            <a href="#"><span class="badge badge-info pull-right">27</span> Clients</a>
                        </li>
                        <li>
                            <a href="#"><span class="badge badge-info pull-right">1,234</span> Users</a>
                        </li>
                        <li>
                            <a href="#"><span class="badge badge-info pull-right">2,221</span> Messages</a>
                        </li>
                        <li>
                            <a href="#"><span class="badge badge-info pull-right">11</span> Reports</a>
                        </li>
                        <li>
                            <a href="#"><span class="badge badge-important pull-right">83</span> Errors</a>
                        </li>
                        <li>
                            <a href="#"><span class="badge badge-warning pull-right">4,231</span> Logs</a>
                        </li>
                    </ul>
                </div>
<% end %>

app/views/layouts/accounts.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aircel Report</title>
  <%= csrf_meta_tags %>
</head>
<style>
 #header {margin:10px;height:50px;border-bottom:1px solid black;}
 #user {float:right;font-size: 25px;}
 .body_data {font-size:12px;font-weight:bold;margin:50px;font-family: 'Sansation', sans-serif;}
 body { margin-top:100px;padding-bottom: 70px;font-family: 'Sansation', sans-serif; }
</style>

<body>
<%= yield %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Aircel | Verify Me" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
<style>
footer {
    height: 50px;
    bottom: 0;
    width: 98%;
}
.navbar .btn-group .btn, .navbar .input-prepend .btn, .navbar .input-append .btn, .navbar .input-prepend .btn-group, .navbar .input-append .btn-group
{width:auto;}
</style>
  </head>

<body style="font-size:12px;">

  <div class="navbar navbar-fluid-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Aircel VerifyMe</a>

        <div class="container-fluid nav-collapse">
          <ul class="nav">
            <% if logged_in? && current_user.admin?   %>
              <li><%= link_to 'Customers', customers_path %></li>						
              <li><%= link_to "Generate Report", reports_path  %></li>
              <li><%= link_to "Servey Detail", serveys_path  %></li>
            <% end %>
          </ul>

        <% if logged_in? %>
          <div class="btn-group" style="float:right;margin-right:20px;">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <%= current_user.name %>
            <b style="color:green">(Admin)</b>
            <span class="caret"></span>
            </button>

            <ul class="dropdown-menu" role="menu">
            <% if current_user.admin? %>  
              <li><%= link_to "Tabs", tabs_path %></li>
              <li><%= link_to "List users", users_path  %></li>
              <li><%= link_to "Add Customer", new_customer_path %></li>    
              <li><%= link_to "List Task on the tab", tab_tasks_path  %></li>      
              <li><%= link_to "Accounts", accounts_path if logged_in? %></li>
              <li class="divider"></li>
              <li><%= link_to "Signout" ,logout_path ,:method => :delete %></li>
            <% else %> 
              <li><%= link_to "Accounts", accounts_path if logged_in? %></li>
              <li class="divider"></li>
              <li><%= link_to "Signout" ,logout_path ,:method => :delete %></li>
            <% end %>
            </ul>
          </div>

          <% else %>

          <div class="btn-group" style="float:right">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
              Login<span class="caret"></span>
            </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Sign-in", login_path %></li>
            <li><%= link_to "New User?", signup_path %><li>
          </ul>    
        <% end %>
         </div>

        </div>
       </div>
      </div>

  <div class="container-fluid">
    <%= bootstrap_flash %>
    <%= yield %>
  <!-- <hr> -->
  </div> <!-- /container -->

</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Aircel-Verify Me" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
<style>
footer {
    height: 50px;
    bottom: 0;
    width: 98%;
}
.navbar .btn-group .btn, .navbar .input-prepend .btn, .navbar .input-append .btn, .navbar .input-prepend .btn-group, .navbar .input-append .btn-group
{width:auto;}
</style>
  <body style="font-size:12px;">

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Aircel VerifyMe</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
			  <% if logged_in? && current_user.admin?   %>
				<li><%= link_to 'Customers', customers_path %></li>						
				<li><%= link_to "Generate Report", reports_path  %></li>
				<li><%= link_to "Servey Detail", serveys_path  %></li>
			  <% end %>
            </ul>

<% if logged_in? %>
<div class="btn-group" style="float:right;margin-right:20px;">
<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
<%= current_user.name %>
  <b style="color:green">[<%= current_user.role_name %>]</b>
  <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <% if current_user.admin? %>  
        <li><%= link_to "Tabs", tabs_path %></li>
        <li><%= link_to "List users", users_path  %></li>
        <li><%= link_to "Add Customer", new_customer_path %></li>    
        <li><%= link_to "List Task on the tab", tab_tasks_path  %></li>      
        <li><%= link_to "Accounts", accounts_path if logged_in? %></li>
        <li class="divider"></li>
        <li><%= link_to "Signout" ,logout_path ,:method => :delete %></li>
      <% else %> 
        <li><%= link_to "Accounts", accounts_path if logged_in? %></li>
        <li class="divider"></li>
        <li><%= link_to "Signout" ,logout_path ,:method => :delete %></li>
    <% end %>
   </ul>
<% else %>
<div class="btn-group" style="float:right">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    Login<span class="caret"></span>
      </button>
<ul class="dropdown-menu" role="menu">
  <li><%= link_to "Sign-in", login_path %></li>
  <li><%= link_to "New User?", signup_path %><li>
</ul>    
<% end %>

    </div>
   </div><!--/.nav-collapse -->
  </div>
 </div>
</div>

<div class="container-fluid">
  <%= bootstrap_flash %>
  <%= yield %>
<hr>
</div> <!-- /container -->
  </body>
</html>